---

- include: package.yml
  tags: [postfix, package]

- include: configuration.yml
  tags: [postfix, configuration]

- name: start/stop postfix service
  service:
    name: postfix
    state: '{{ postfix_service_state }}'
    enabled: '{{ postfix_service_enabled }}'
  tags: [postfix, service]
