---

- include: package.yml
  tags: package

- include: configuration.yml
  tags: configuration

- name: start/stop postfix service
  service:
    name: postfix
    state: '{{ postfix_service_state }}'
    enabled: '{{ postfix_service_enabled }}'
  tags: service